### ISSUE TITLE
Error while logging in when providing the login credentials in the compose-file

### ISSUE THREAD

**Issue by Soljanka** [mm28ajos/docker-dynamic-dns-netcup-api#4]
Hello, I double checked my CUSTOMERNR, APIKEY and APIPASSWORD couple of times already and waited one day between retries, yet I always get the following error no matter what:

`netcup-ddns-1  | [2025/06/25 14:27:35 +0000][ERROR] Error while logging in: More than 180 requests per minute. Please wait and retry later. Please contact our customer service to find out if the limitation of requests can be increased. [ADDITIONAL INFORMATION: This error from the netcup DNS API also often indicates that you have supplied wrong API credentials. Please check them in the config file.] Exiting.`

This is my compose-file:
```
services:
  netcup-ddns:
    image: mm28ajos/docker-dynamic-dns-netcup-api:latest
    container_name: netcup-ddns-1
    restart: unless-stopped
    environment:
      - CUSTOMERNR=123456
      - APIKEY=abcdefghijklmnopqrstuvwxyz
      - APIPASSWORD=abcdefghijklmnopqrstuvwxyz
      - DOMAIN=meinedomain.de
      - HOSTIPv4=*, @
      - USE_IPV4=true
      - USE_IPV6=false
      - SLEEP_INTERVAL_SEC=900

```
